# Generated by Django 3.1.7 on 2021-05-08 14:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Chat', '0002_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='roomname',
            new_name='room_name',
        ),
        migrations.AlterField(
            model_name='chat',
            name='members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
