# Generated by Django 3.1.7 on 2021-05-09 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0004_auto_20210508_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(blank=True, choices=[('txt', 'متن'), ('img', 'عکس')], max_length=3, null=True, verbose_name='نوع پیام'),
        ),
        migrations.AlterField(
            model_name='message',
            name='related_chat',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Chat.chat', verbose_name='گروه مقصد'),
        ),
    ]
